version: '3.4'

services:
  shopping.client:
    platform: linux/amd64
    image: ${DOCKER_REGISTRY-}shopping
    build:
      context: .
      dockerfile: Shopping.Client/Dockerfile

  shopping.api:
    image: ${DOCKER_REGISTRY-}shopping
    build:
      context: .
      dockerfile: Shopping.API/Dockerfile

