version: '3.4'

services:
  shopping.client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  shopping.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

